// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Account struct {
	ID           string      `json:"id"`
	UserID       int32       `json:"userId"`
	Name         string      `json:"name"`
	Type         AccountType `json:"type"`
	DefaultMoney float64     `json:"defaultMoney"`
	Amount       float64     `json:"amount"`
	IconID       *string     `json:"iconId,omitempty"`
	CreatedAt    string      `json:"createdAt"`
	UpdatedAt    string      `json:"updatedAt"`
}

type Category struct {
	ID             string       `json:"id"`
	UserID         int32        `json:"userId"`
	Name           string       `json:"name"`
	CategoriesType CategoryType `json:"categoriesType"`
	IconID         *string      `json:"iconId,omitempty"`
	CreatedAt      string       `json:"createdAt"`
	UpdatedAt      string       `json:"updatedAt"`
}

type MonthlyExpenseAnalysis struct {
	ID        string  `json:"id"`
	UserID    int32   `json:"userId"`
	Spending  float64 `json:"spending"`
	Income    float64 `json:"income"`
	Month     string  `json:"month"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type Mutation struct {
}

type NewAccount struct {
	Name         string      `json:"name"`
	Type         AccountType `json:"type"`
	DefaultMoney float64     `json:"defaultMoney"`
	IconID       *string     `json:"iconId,omitempty"`
}

type NewCategory struct {
	Name           string       `json:"name"`
	CategoriesType CategoryType `json:"categoriesType"`
	IconID         *string      `json:"iconId,omitempty"`
}

type NewTransaction struct {
	AccountID  string  `json:"accountId"`
	CategoryID string  `json:"categoryId"`
	Amount     float64 `json:"amount"`
	Notes      *string `json:"notes,omitempty"`
	Date       *string `json:"date,omitempty"`
}

type Query struct {
}

type Transaction struct {
	ID           string  `json:"id"`
	UserID       int32   `json:"userId"`
	AccountName  string  `json:"accountName"`
	CategoryName string  `json:"categoryName"`
	Amount       float64 `json:"amount"`
	Notes        *string `json:"notes,omitempty"`
	Date         string  `json:"date"`
	CreatedAt    string  `json:"createdAt"`
	UpdatedAt    string  `json:"updatedAt"`
}

type UpdateAccount struct {
	Name         *string      `json:"name,omitempty"`
	Type         *AccountType `json:"type,omitempty"`
	DefaultMoney *float64     `json:"defaultMoney,omitempty"`
	IconID       *string      `json:"iconId,omitempty"`
}

type UpdateCategory struct {
	Name   *string `json:"name,omitempty"`
	IconID *string `json:"iconId,omitempty"`
}

type UpdateTransaction struct {
	AccountID  *string  `json:"accountId,omitempty"`
	CategoryID *string  `json:"categoryId,omitempty"`
	Amount     *float64 `json:"amount,omitempty"`
	Notes      *string  `json:"notes,omitempty"`
	Date       *string  `json:"date,omitempty"`
}

type AccountType string

const (
	AccountTypeCash       AccountType = "CASH"
	AccountTypeBank       AccountType = "BANK"
	AccountTypeEWallet    AccountType = "E_WALLET"
	AccountTypeReceivable AccountType = "RECEIVABLE"
	AccountTypePayable    AccountType = "PAYABLE"
	AccountTypeInvestment AccountType = "INVESTMENT"
	AccountTypeCredit     AccountType = "CREDIT"
)

var AllAccountType = []AccountType{
	AccountTypeCash,
	AccountTypeBank,
	AccountTypeEWallet,
	AccountTypeReceivable,
	AccountTypePayable,
	AccountTypeInvestment,
	AccountTypeCredit,
}

func (e AccountType) IsValid() bool {
	switch e {
	case AccountTypeCash, AccountTypeBank, AccountTypeEWallet, AccountTypeReceivable, AccountTypePayable, AccountTypeInvestment, AccountTypeCredit:
		return true
	}
	return false
}

func (e AccountType) String() string {
	return string(e)
}

func (e *AccountType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AccountType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AccountType", str)
	}
	return nil
}

func (e AccountType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AccountType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AccountType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CategoryType string

const (
	CategoryTypeExpense  CategoryType = "EXPENSE"
	CategoryTypeIncome   CategoryType = "INCOME"
	CategoryTypeTransfer CategoryType = "TRANSFER"
)

var AllCategoryType = []CategoryType{
	CategoryTypeExpense,
	CategoryTypeIncome,
	CategoryTypeTransfer,
}

func (e CategoryType) IsValid() bool {
	switch e {
	case CategoryTypeExpense, CategoryTypeIncome, CategoryTypeTransfer:
		return true
	}
	return false
}

func (e CategoryType) String() string {
	return string(e)
}

func (e *CategoryType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CategoryType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CategoryType", str)
	}
	return nil
}

func (e CategoryType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CategoryType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CategoryType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
