package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"ExpenseServer/graph/model"
	"context"
	"database/sql"
	"fmt"
	"strconv"
)

// CreateAccount is the resolver for the createAccount field.
func (r *mutationResolver) CreateAccount(ctx context.Context, input model.NewAccount) (*model.Account, error) {
	userID, err := getUserID(ctx)
	if err != nil {
		return nil, err
	}

	iconID := ""
	if input.IconID != nil {
		iconID = *input.IconID
	}

	res, err := r.DB.Exec("INSERT INTO accounts (user_id, name, type, default_money, amount, icon_id) VALUES (?, ?, ?, ?, ?, ?)",
		userID, input.Name, input.Type.String(), input.DefaultMoney, input.DefaultMoney, iconID)
	if err != nil {
		return nil, err
	}

	id, _ := res.LastInsertId()
	return &model.Account{
		ID:           strconv.FormatInt(id, 10),
		UserID:       int32(userID),
		Name:         input.Name,
		Type:         input.Type,
		DefaultMoney: input.DefaultMoney,
		Amount:       input.DefaultMoney,
		IconID:       input.IconID,
		CreatedAt:    "",
		UpdatedAt:    "",
	}, nil
}

// UpdateAccount is the resolver for the updateAccount field.
func (r *mutationResolver) UpdateAccount(ctx context.Context, id string, input model.UpdateAccount) (*model.Account, error) {
	userID, err := getUserID(ctx)
	if err != nil {
		return nil, err
	}

	var name, typeStr, iconIDStr string
	var defaultMoney, amount float64
	err = r.DB.QueryRow("SELECT name, type, default_money, amount, icon_id FROM accounts WHERE id = ? AND user_id = ?", id, userID).Scan(&name, &typeStr, &defaultMoney, &amount, &iconIDStr)
	if err != nil {
		return nil, err
	}

	if input.IconID != nil {
		iconIDStr = *input.IconID
	}
	if input.Name != nil {
		name = *input.Name
	}
	if input.Type != nil {
		typeStr = input.Type.String()
	}
	if input.DefaultMoney != nil {
		amount += *input.DefaultMoney - defaultMoney
		defaultMoney = *input.DefaultMoney
	}

	_, err = r.DB.Exec("UPDATE accounts SET name = ?, type = ?, default_money = ?, amount = ?, icon_id = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND user_id = ?",
		name, typeStr, defaultMoney, amount, iconIDStr, id, userID)
	if err != nil {
		return nil, err
	}

	return &model.Account{
		ID:           id,
		UserID:       int32(userID),
		Name:         name,
		Type:         model.AccountType(typeStr),
		DefaultMoney: defaultMoney,
		Amount:       amount,
		IconID:       &iconIDStr,
	}, nil
}

// DeleteAccount is the resolver for the deleteAccount field.
func (r *mutationResolver) DeleteAccount(ctx context.Context, id string) (bool, error) {
	userID, err := getUserID(ctx)
	if err != nil {
		return false, err
	}

	_, err = r.DB.Exec("DELETE FROM accounts WHERE id = ? AND user_id = ?", id, userID)
	return err == nil, err
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input model.NewCategory) (*model.Category, error) {
	userID, err := getUserID(ctx)
	if err != nil {
		return nil, err
	}

	iconID := ""
	if input.IconID != nil {
		iconID = *input.IconID
	}

	res, err := r.DB.Exec("INSERT INTO categories (user_id, name, categories_type, icon_id) VALUES (?, ?, ?, ?)",
		userID, input.Name, input.CategoriesType.String(), iconID)
	if err != nil {
		return nil, err
	}

	id, _ := res.LastInsertId()
	return &model.Category{
		ID:             strconv.FormatInt(id, 10),
		UserID:         int32(userID),
		Name:           input.Name,
		CategoriesType: input.CategoriesType,
		IconID:         input.IconID,
		CreatedAt:      "",
		UpdatedAt:      "",
	}, nil
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id string, input model.UpdateCategory) (*model.Category, error) {
	userID, err := getUserID(ctx)
	if err != nil {
		return nil, err
	}

	var name, categoriesTypeStr, iconIDStr string
	err = r.DB.QueryRow("SELECT name, categories_type, icon_id FROM categories WHERE id = ? AND user_id = ?", id, userID).Scan(&name, &categoriesTypeStr, &iconIDStr)
	if err != nil {
		return nil, err
	}

	if input.IconID != nil {
		iconIDStr = *input.IconID
	}
	if input.Name != nil {
		name = *input.Name
	}

	_, err = r.DB.Exec("UPDATE categories SET name = ?, icon_id = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND user_id = ?",
		name, iconIDStr, id, userID)
	if err != nil {
		return nil, err
	}

	return &model.Category{
		ID:             id,
		UserID:         int32(userID),
		Name:           name,
		CategoriesType: model.CategoryType(categoriesTypeStr),
		IconID:         &iconIDStr,
	}, nil
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id string) (bool, error) {
	userID, err := getUserID(ctx)
	if err != nil {
		return false, err
	}

	_, err = r.DB.Exec("DELETE FROM categories WHERE id = ? AND user_id = ?", id, userID)
	return err == nil, err
}

// CreateTransaction is the resolver for the createTransaction field.
func (r *mutationResolver) CreateTransaction(ctx context.Context, input model.NewTransaction) (*model.Transaction, error) {
	userID, err := getUserID(ctx)
	if err != nil {
		return nil, err
	}

	var accountName, categoryName string
	err = r.DB.QueryRow("SELECT name FROM accounts WHERE id = ? AND user_id = ?", input.AccountID, userID).Scan(&accountName)
	if err != nil {
		return nil, fmt.Errorf("account not found or unauthorized: %v", err)
	}

	err = r.DB.QueryRow("SELECT name FROM categories WHERE id = ? AND user_id = ?", input.CategoryID, userID).Scan(&categoryName)
	if err != nil {
		return nil, fmt.Errorf("category not found or unauthorized: %v", err)
	}

	notes := ""
	if input.Notes != nil {
		notes = *input.Notes
	}

	dateStr := ""
	if input.Date != nil {
		dateStr = *input.Date
	}
	if dateStr == "" {
		_ = r.DB.QueryRow("SELECT date('now')").Scan(&dateStr)
	}

	res, err := r.DB.Exec("INSERT INTO transactions (user_id, account_name, category_name, amount, notes, date) VALUES (?, ?, ?, ?, ?, ?)",
		userID, accountName, categoryName, input.Amount, notes, dateStr)
	if err != nil {
		return nil, err
	}

	id, _ := res.LastInsertId()

	updateBalanceByNames(r.DB, userID, accountName, input.Amount, categoryName, dateStr)

	return &model.Transaction{
		ID:           strconv.FormatInt(id, 10),
		UserID:       int32(userID),
		AccountName:  accountName,
		CategoryName: categoryName,
		Amount:       input.Amount,
		Notes:        input.Notes,
		Date:         dateStr,
		CreatedAt:    "",
		UpdatedAt:    "",
	}, nil
}

// UpdateTransaction is the resolver for the updateTransaction field.
func (r *mutationResolver) UpdateTransaction(ctx context.Context, id string, input model.UpdateTransaction) (*model.Transaction, error) {
	userID, err := getUserID(ctx)
	if err != nil {
		return nil, err
	}

	var accountName, categoryName, notes, dateStr string
	var amount float64
	err = r.DB.QueryRow("SELECT account_name, category_name, amount, notes, date FROM transactions WHERE id = ? AND user_id = ?", id, userID).Scan(&accountName, &categoryName, &amount, &notes, &dateStr)
	if err != nil {
		return nil, err
	}

	revertBalanceByNames(r.DB, userID, accountName, amount, categoryName, dateStr)

	if input.AccountID != nil {
		err = r.DB.QueryRow("SELECT name FROM accounts WHERE id = ? AND user_id = ?", *input.AccountID, userID).Scan(&accountName)
		if err != nil {
			return nil, fmt.Errorf("account not found")
		}
	}
	if input.CategoryID != nil {
		err = r.DB.QueryRow("SELECT name FROM categories WHERE id = ? AND user_id = ?", *input.CategoryID, userID).Scan(&categoryName)
		if err != nil {
			return nil, fmt.Errorf("category not found")
		}
	}
	if input.Amount != nil {
		amount = *input.Amount
	}
	if input.Notes != nil {
		notes = *input.Notes
	}
	if input.Date != nil {
		dateStr = *input.Date
	}

	_, err = r.DB.Exec("UPDATE transactions SET account_name = ?, category_name = ?, amount = ?, notes = ?, date = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ? AND user_id = ?",
		accountName, categoryName, amount, notes, dateStr, id, userID)
	if err != nil {
		return nil, err
	}

	updateBalanceByNames(r.DB, userID, accountName, amount, categoryName, dateStr)

	return &model.Transaction{
		ID:           id,
		UserID:       int32(userID),
		AccountName:  accountName,
		CategoryName: categoryName,
		Amount:       amount,
		Notes:        &notes,
		Date:         dateStr,
	}, nil
}

// DeleteTransaction is the resolver for the deleteTransaction field.
func (r *mutationResolver) DeleteTransaction(ctx context.Context, id string) (bool, error) {
	userID, err := getUserID(ctx)
	if err != nil {
		return false, err
	}

	var accountName, categoryName, dateStr string
	var amount float64
	err = r.DB.QueryRow("SELECT account_name, category_name, amount, date FROM transactions WHERE id = ? AND user_id = ?", id, userID).Scan(&accountName, &categoryName, &amount, &dateStr)
	if err != nil {
		return false, err
	}

	revertBalanceByNames(r.DB, userID, accountName, amount, categoryName, dateStr)

	_, err = r.DB.Exec("DELETE FROM transactions WHERE id = ? AND user_id = ?", id, userID)
	return err == nil, err
}

// Accounts is the resolver for the accounts field.
func (r *queryResolver) Accounts(ctx context.Context) ([]*model.Account, error) {
	userID, err := getUserID(ctx)
	if err != nil {
		return nil, err
	}

	var items []*model.Account
	rows, err := r.DB.Query("SELECT id, name, type, default_money, amount, icon_id, created_at, updated_at FROM accounts WHERE user_id = ?", userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var acc model.Account
		var id int64
		var typeStr string
		var iconID sql.NullString
		if err := rows.Scan(&id, &acc.Name, &typeStr, &acc.DefaultMoney, &acc.Amount, &iconID, &acc.CreatedAt, &acc.UpdatedAt); err != nil {
			return nil, err
		}
		acc.ID = strconv.FormatInt(id, 10)
		acc.Type = model.AccountType(typeStr)
		acc.UserID = int32(userID)
		if iconID.Valid {
			str := iconID.String
			acc.IconID = &str
		}
		items = append(items, &acc)
	}
	return items, nil
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context) ([]*model.Category, error) {
	userID, err := getUserID(ctx)
	if err != nil {
		return nil, err
	}

	var items []*model.Category
	rows, err := r.DB.Query("SELECT id, name, categories_type, icon_id, created_at, updated_at FROM categories WHERE user_id = ?", userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var cat model.Category
		var id int64
		var typeStr string
		var iconID sql.NullString
		if err := rows.Scan(&id, &cat.Name, &typeStr, &iconID, &cat.CreatedAt, &cat.UpdatedAt); err != nil {
			return nil, err
		}
		cat.ID = strconv.FormatInt(id, 10)
		cat.CategoriesType = model.CategoryType(typeStr)
		cat.UserID = int32(userID)
		if iconID.Valid {
			str := iconID.String
			cat.IconID = &str
		}
		items = append(items, &cat)
	}
	return items, nil
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context) ([]*model.Transaction, error) {
	userID, err := getUserID(ctx)
	if err != nil {
		return nil, err
	}

	query := "SELECT id, account_name, category_name, amount, notes, date, created_at, updated_at FROM transactions WHERE user_id = ? ORDER BY date DESC"

	var items []*model.Transaction
	rows, err := r.DB.Query(query, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	for rows.Next() {
		var t model.Transaction
		var id int64
		var notes sql.NullString
		if err := rows.Scan(&id, &t.AccountName, &t.CategoryName, &t.Amount, &notes, &t.Date, &t.CreatedAt, &t.UpdatedAt); err != nil {
			return nil, err
		}
		t.ID = strconv.FormatInt(id, 10)
		t.UserID = int32(userID)
		if notes.Valid {
			str := notes.String
			t.Notes = &str
		}
		items = append(items, &t)
	}
	return items, nil
}

// MonthlyExpenseAnalysis is the resolver for the monthlyExpenseAnalysis field.
func (r *queryResolver) MonthlyExpenseAnalysis(ctx context.Context, month *string) ([]*model.MonthlyExpenseAnalysis, error) {
	userID, err := getUserID(ctx)
	if err != nil {
		return nil, err
	}

	query := "SELECT id, spending, income, month, created_at, updated_at FROM monthly_expense_analysis WHERE user_id = ?"
	var args []interface{}
	args = append(args, userID)

	if month != nil {
		query += " AND month = ?"
		args = append(args, *month)
	}

	rows, err := r.DB.Query(query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []*model.MonthlyExpenseAnalysis
	for rows.Next() {
		var t model.MonthlyExpenseAnalysis
		var id int64
		if err := rows.Scan(&id, &t.Spending, &t.Income, &t.Month, &t.CreatedAt, &t.UpdatedAt); err != nil {
			return nil, err
		}
		t.ID = strconv.FormatInt(id, 10)
		t.UserID = int32(userID)
		items = append(items, &t)
	}
	return items, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }


